# Generated by Django 2.2.4 on 2019-08-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaperurl',
            name='enter_url',
            field=models.CharField(max_length=100),
        ),
    ]
