# Generated by Django 2.2.4 on 2019-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_analysis', '0002_auto_20190820_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=400)),
                ('date1', models.CharField(max_length=10)),
            ],
        ),
    ]
