# Generated by Django 2.2.4 on 2019-08-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_analysis', '0003_data1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data1',
        ),
    ]
