# Generated by Django 2.2.4 on 2019-10-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_analysis', '0004_delete_data1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_pdf', models.CharField(max_length=100)),
            ],
        ),
    ]
